# Generated by Django 5.1.6 on 2025-02-26 10:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='item_image',
            field=models.ImageField(default='images/default.png', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='item_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='item_price',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(limit_value=10000, message='Product too expensive!'), django.core.validators.MinValueValidator(limit_value=0, message='Please set a higher price')]),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='item_rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5),
        ),
    ]
