# Generated by Django 5.1.6 on 2025-03-05 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_menuitem_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='item_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='menuitem',
            old_name='item_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='menuitem',
            old_name='item_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='menuitem',
            old_name='item_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='menuitem',
            old_name='item_rating',
            new_name='rating',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
