# Generated by Django 5.1.7 on 2025-03-11 11:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_alter_menuitem_options_alter_menuitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MaxValueValidator(limit_value=10000, message='Product too expensive!'), django.core.validators.MinValueValidator(limit_value=0, message='Please set a higher price')]),
        ),
    ]
