# Generated by Django 5.1.6 on 2025-03-03 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_order_order_status'),
        ('management', '0002_alter_menuitem_item_image_alter_menuitem_item_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='item_total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='management.menuitem'),
        ),
    ]
