# Generated by Django 5.1.6 on 2025-02-25 09:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('item_price', models.IntegerField(validators=[django.core.validators.MaxValueValidator(limit_value=10000, message='Product too expensive!'), django.core.validators.MinValueValidator(limit_value=0, message='Please set a higher price')])),
                ('item_description', models.TextField()),
                ('item_rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('item_image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
